app_backend_animal:
    resource: |
        alias: app.animal
        section: backend
        except: ['show']
        redirect: update
        grid: app_backend_animal
        vars:
            all:
                subheader: app.ui.managing_animals
                templates:
                    form: "backend/animal/_form.html.twig"
            index:
                icon: 'cat' # choose an icon that will be displayed next to the subheader
        templates: backend/crud
    type: sylius.resource
