app_backend_booking:
    resource: |
        alias: app.booking
        section: backend
        except: ['show']
        redirect: update
        grid: app_backend_booking
        vars:
            all:
                subheader: app.ui.managing_bookings
            index:
                icon: 'fax'
        templates: backend/crud
    type: sylius.resource
