app_backend_pet:
    resource: |
        alias: app.pet
        section: backend
        except: ['index']
        redirect: update
        grid: app_backend_pet
        vars:
            all:
                subheader: app.ui.managing_pets
                templates:
                    form: "backend/pet/_form.html.twig"
        templates: backend/crud
    type: sylius.resource

app_backend_pet_show:
    methods: [GET]
    path: /pets/{id}
    defaults:
        _controller: app.controller.pet:showAction
        _sylius:
            section: backend
            template: backend/pet/show.html.twig
            vars:
                toolbar: 'backend/pet/show/_toolbar.html.twig'

app_backend_pet_index:
    path: /pets/
    methods: [GET]
    defaults:
        _controller: app.controller.pet:indexAction
        _sylius:
            section: backend
            permission: true
            grid: app_backend_pet
            template: "backend/pet/index.html.twig"
            vars:
                subheader: app.ui.managing_pets
                icon: cat

app_backend_pet_per_taxon_index:
    path: /pets/taxon/{taxonId}
    methods: [GET]
    defaults:
        _controller: app.controller.pet:indexAction
        _sylius:
            section: backend
            permission: true
            grid: app_backend_pet
            template: "backend/pet/index.html.twig"
            vars:
                subheader: app.ui.managing_pets
                icon: cat
