# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        thumbnail:
            filters:
                auto_rotate: ~
                thumbnail: { size: [ 60, 60 ], mode: outbound }
        pet_grid:
            filters:
                auto_rotate: ~
                upscale: { min: [500, 344] }
                thumbnail: { size: [500, 344], mode: outbound }
        app_frontend_pet_show:
            filters:
                auto_rotate: ~
                thumbnail: { size: [400, 400], mode: outbound }
        app_frontend_pet_details:
            filters:
                auto_rotate: ~
                thumbnail: { size: [300, 300], mode: outbound }
