# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        # @see http://symfony.com/doc/current/bundles/LiipImagineBundle/filters.html
        cache: ~
        default:
            filters:
                auto_rotate: ~
                relative_resize: { scale: 1 }
        thumbnail:
            filters:
                auto_rotate: ~
                thumbnail: { size: [60, 60], mode: outbound }
        pet_grid:
            filters:
                auto_rotate: ~
                upscale: { min: [500, 344] }
                thumbnail: { size: [500, 344], mode: outbound }
        app_backend_admin_user_avatar_thumbnail:
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
