sylius_taxonomy:
    driver: doctrine/orm # Configure the doctrine orm driver used in documentation.
    resources:
        taxon:
            classes:
                model: App\Entity\Taxonomy\Taxon
                # form: App\Form\Type\Taxonomy\TaxonType
                # repository: App\Repository\TaxonRepository
