vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        animal_image:
            uri_prefix: /media/animal
            upload_destination: '%kernel.project_dir%/public/media/animal'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
