winzou_state_machine:
    my_bundle_booking:
        class: App\Entity\Booking\Booking
        property_path: status
        graph: app_booking
        states:
            - new
            - validated
            - canceled
            - finished
        transitions:
            validate:
                from: [new]
                to: validated
            cancel:
                from: [new]
                to: canceled
        callbacks:
            before:
                update_booking_validatation_date:
                    on:   'validate'
                    do:   ['@app.modifier.booking', 'updateValidationDate']
                    args: ['object']
            after:
                email_on_cancel:
                    on:   'cancel'
                    do:   ['@app.sender.email', 'sendEmailForCanceledBooking']
                    args: ['object']
