winzou_state_machine:
    my_bundle_booking:
        class: App\Entity\Booking\Booking
        property_path: status
        graph: app_booking
        states:
            - new
            - family_contacted
            - visit_scheduled
            - canceled
            - finished
            - refused
        transitions:
            contact_family:
                from: [new]
                to: family_contacted
            schedule_a_visit:
                from: [family_contacted]
                to: visit_scheduled
            finish:
                from: [visit_scheduled]
                to: finished
            cancel:
                from: [new, family_contacted, visit_scheduled]
                to: canceled
            refuse:
                from: [new, family_contacted, visit_scheduled]
                to: refused
        callbacks:
            before:
                update_booking_family_contact_date:
                    on:   ['contact_family']
                    do:   ['@app.modifier.booking', 'updateFamilyContactDate']
                    args: ['object']
            after:
                email_on_cancel:
                    on:   ['cancel']
                    do:   ['@app.sender.email', 'sendEmailForCanceledBooking']
                    args: ['object']
                update_pet_status_on_cancel_or_refuse:
                    on:   ['cancel', 'refuse']
                    do:   ['@sm.callback.cascade_transition', 'apply']
                    args: ['object.getPet()', 'event', "'unbook'", "'app_pet'"]
                update_pet_status_on_finish:
                    on:   ['finish']
                    do:   ['@sm.callback.cascade_transition', 'apply']
                    args: ['object.getPet()', 'event', "'adopt'", "'app_pet'"]

    app_pet:
        class: App\Entity\Animal\Pet
        property_path: status
        graph: app_pet
        states:
            - new
            - bookable
            - booked
            - adopted
        transitions:
            validate:
                from: [new]
                to: bookable
            book:
                from: [bookable]
                to: booked
            adopt:
                from: [booked]
                to: adopted
            unbook:
                from: [booked]
                to: bookable
        callbacks:
            after:
                create_booking_on_book:
                    on:   ['book']
                    do:   ['@app.modifier.pet', 'createBooking']
                    args: ['object']
