app_frontend_homepage:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'frontend/homepage/index.html.twig'

app_account:
    resource: "frontend/account.yaml"
    prefix: "account"

app_frontend_pet:
    resource: "frontend/pet.yaml"

sylius_security:
    resource: "frontend/security.yaml"

app_frontend_partial:
    resource: "frontend/partial.yaml"
    prefix: "/_partial"

app_frontend_ajax:
    resource: "frontend/ajax.yaml"
    prefix: "/_ajax"

app_frontend_booking:
    resource: "frontend/booking.yaml"
