App\Message\ResetPasswordRequest:
    attributes:
        messenger: true
        output: false
    itemOperations: []
    collectionOperations:
        post:
            path: /request_password
            openapi_context:
                summary: Request a new password
