App\Message\ResetPassword:
    attributes:
        messenger: true
        output: false
    itemOperations: []
    collectionOperations:
        post:
            path: /reset_password/{token}
            openapi_context:
                summary: Reset password
