App\Entity\Taxonomy\Taxon:
    attributes:
        normalization_context:
            groups: ['taxon:read']
    itemOperations:
        get:
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
            openapi_context:
                tags: [ Internal ]
    collectionOperations:
        get: null
    properties:
        pets:
            subresource:
                resourceClass: 'App\Entity\Animal\Pet'
                collection: true
