default:
    suites:
        ui_viewing_animals:
            contexts:
                - App\Tests\Behat\Context\Hook\DoctrineORMContext

                - App\Tests\Behat\Context\Domain\AnimalContext

                - App\Tests\Behat\Context\Setup\AnimalContext
                - App\Tests\Behat\Context\Setup\TaxonContext

                - App\Tests\Behat\Context\Transform\AnimalContext
                - App\Tests\Behat\Context\Transform\SharedStorageContext
                - App\Tests\Behat\Context\Transform\TaxonContext

                - App\Tests\Behat\Context\Ui\Frontend\AnimalContext
            filters:
                tags: "@viewing_animals && @ui"
