sylius_frontend_account_dashboard:
    path: /dashboard
    methods: [GET]
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: sylius_frontend_account_booking

sylius_frontend_account_profile_update:
    path: /profile/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.customer:updateAction
        _sylius:
            template: "frontend/account/updateProfile.html.twig"
            form: Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType
            repository:
                method: find
                arguments:
                    - expr:service('App\\Context\\CustomerContext').getCustomer()
            flash: sylius.customer.update_profile
            redirect:
                route: sylius_frontend_account_dashboard
                parameters: {}

sylius_frontend_account_change_password:
    path: /change-password
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.app_user:changePasswordAction
        _sylius:
            template: "frontend/account/changePassword.html.twig"
            redirect: sylius_frontend_account_dashboard
