app_backend_partial_booking_latest:
    path: /latest/{count}
    methods: [GET]
    defaults:
        _controller: app.controller.booking::indexAction
        _sylius:
            repository:
                method: findLatest
                arguments: ['!!int $count']
            template: $template
