app_frontend_animal_index:
    methods: [GET]
    path: /animals/
    defaults:
        _controller: app.controller.animal::indexAction
        _sylius:
            grid: app_frontend_animal
            template: frontend/animal/index.html.twig

app_frontend_animal_show:
    methods: [GET]
    path: /animals/{slug}
    defaults:
        _controller: app.controller.animal::showAction
        _sylius:
            template: frontend/animal/show.html.twig
