app_frontend_booking_show:
    methods: [GET]
    path: /bookings/{id}
    defaults:
        _controller: app.controller.booking::showAction
        _sylius:
            template: frontend/booking/show.html.twig

app_frontend_booking_summary:
    path: /bookings/{slug}/summary
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'frontend/booking/summary.html.twig'

app_frontend_booking_confirmation:
    path: /bookings/{slug}/confirmation
    defaults:
        _controller: App\Controller\BookingConfirmationController
