sylius_frontend_partial_taxon_root_nodes:
    path: /taxons/root-nodes
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            template: $template
            repository:
                method: findRootNodes
    requirements:
        template: "[^?]+"
