sylius_frontend_partial_taxon_root_nodes:
    path: /taxons/root-nodes
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            template: $template
            repository:
                method: findRootNodes
    requirements:
        template: "[^?]+"

app_frontend_partial_animal_latest:
    path: /latest/{count}
    methods: [GET]
    defaults:
        _controller: app.controller.pet::indexAction
        _sylius:
            repository:
                method: findLatest
                arguments: ['!!int $count']
            template: $template
    requirements:
        template: "[^?]+"

app_frontend_partial_pet_show:
    path: /pets/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon::showAction
        _sylius:
            repository:
                method: findOneBySlug
                arguments:
                    - $slug
                    - '%locale%'
            template: $template
    requirements:
        template: "[^?]+"
        slug: "[^?]+"
