app_frontend_pet_index:
    methods: [GET]
    path: /pets/
    defaults:
        _controller: app.controller.pet::indexAction
        _sylius:
            grid: app_frontend_pet
            template: frontend/pet/index.html.twig

app_frontend_pet_show:
    methods: [GET]
    path: /pets/{slug}
    defaults:
        _controller: app.controller.pet::showAction
        _sylius:
            template: frontend/pet/show.html.twig

app_frontend_pet_per_taxon_index:
    methods: [GET]
    path: /pets/taxon/{slug}
    defaults:
        _controller: app.controller.pet::indexAction
        _sylius:
            grid: app_frontend_pet_per_taxon
            template: frontend/pet/index.html.twig
    requirements:
        slug: .+

app_frontend_pet_book:
    methods: [POST]
    path: /pets/{slug}/book
    defaults:
        _controller: app.controller.pet::applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: app_pet
                transition: book
            csrf_protection: false
            redirect:
                route: app_frontend_booking_confirmation
                parameters: { slug: resource.slug }
