app_frontend_pet_index:
    methods: [GET]
    path: /pets/
    defaults:
        _controller: app.controller.pet::indexAction
        _sylius:
            grid: app_frontend_pet
            template: frontend/pet/index.html.twig

app_frontend_pet_show:
    methods: [GET]
    path: /pets/{slug}
    defaults:
        _controller: app.controller.pet::showAction
        _sylius:
            template: frontend/pet/show.html.twig

app_frontend_pet_per_taxon_index:
    methods: [GET]
    path: /pets/taxon/{slug}
    defaults:
        _controller: app.controller.pet::indexAction
        _sylius:
            grid: app_frontend_pet
            template: frontend/pet/index.html.twig
    requirements:
        slug: .+
