imports:
    - suites/cli/installer.yaml

    # Uncomment these lines if you use monofony/front-pack
    - suites/ui/account/customer.yaml
    - suites/ui/account/login.yaml
    - suites/ui/account/registration.yaml

    - suites/ui/admin/dashboard.yaml
    - suites/ui/booking/managing_bookings.yaml
    - suites/ui/customer/managing_customers.yaml
    - suites/ui/user/managing_administrators.yaml
    - suites/ui/pet/booking_pets.yaml
    - suites/ui/pet/managing_pets.yaml
    - suites/ui/pet/viewing_pets.yaml
