#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_backend_pet_index:
    path: /admin/pets/
    methods: [GET]
    defaults:
        _controller: app.controller.pet:indexAction
        _sylius:
            section: backend
            permission: true
            grid: app_pet
            template: "backend/pet/index.html.twig"
            vars:
                subheader: app.ui.manage_your_pets
                icon: cat

app_backend_pet_per_taxon_index:
    path: /admin/pets/taxon/{taxonId}
    methods: [GET]
    defaults:
        _controller: app.controller.pet:indexAction
        _sylius:
            section: backend
            permission: true
            grid: app_pet
            template: "backend/pet/index.html.twig"
            vars:
                subheader: app.ui.manage_your_pets
                icon: cat

sylius_backend_taxon_index:
    path: /admin/taxa/
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
        route: sylius_backend_taxon_create
        permanent: true

sylius_backend_ajax_taxon_move:
    path: /admin/taxa/{id}/move
    methods: [PUT]
    defaults:
        _controller: sylius.controller.taxon:updateAction
        _format: json
        _sylius:
            permission: true
            form: App\Form\Type\Taxonomy\TaxonPositionType
