default:
    suites:
        ui_viewing_pets:
            contexts:
                - App\Tests\Behat\Context\Hook\DoctrineORMContext

                - App\Tests\Behat\Context\Domain\PetContext

                - App\Tests\Behat\Context\Setup\PetContext
                - App\Tests\Behat\Context\Setup\TaxonContext

                - App\Tests\Behat\Context\Transform\PetContext
                - App\Tests\Behat\Context\Transform\SharedStorageContext
                - App\Tests\Behat\Context\Transform\TaxonContext

                - App\Tests\Behat\Context\Ui\Frontend\PetContext
            filters:
                tags: "@viewing_pets && @ui"
