default:
    suites:
        ui_booking_pets:
            contexts:
                - App\Tests\Behat\Context\Hook\DoctrineORMContext

                # - App\Tests\Behat\Context\Domain\BookingContext
                - App\Tests\Behat\Context\Domain\PetContext

                - App\Tests\Behat\Context\Setup\AppSecurityContext
                - App\Tests\Behat\Context\Setup\LocaleContext
                - App\Tests\Behat\Context\Setup\PetContext
                - App\Tests\Behat\Context\Setup\TaxonContext
                - App\Tests\Behat\Context\Setup\UserContext

                - App\Tests\Behat\Context\Transform\PetContext
                - App\Tests\Behat\Context\Transform\SharedStorageContext
                - App\Tests\Behat\Context\Transform\TaxonContext

                - App\Tests\Behat\Context\Ui\Frontend\BookingContext
            filters:
                tags: "@booking_pets&&@ui"
