sylius_grid:
    grids:
        app_frontend_animal:
            driver:
                name: doctrine/orm
                options:
                    class: '%app.model.animal.class%'
            limits: [15]
            sorting:
                name: asc
            fields:
                name:
                    type: string
                    sortable: null
