sylius_grid:
    grids:
        app_frontend_pet:
            driver:
                name: doctrine/orm
                options:
                    class: '%app.model.pet.class%'
                    repository:
                        method: createListQuerySlugBuilder
                        arguments: ['%locale%', $slug]
            limits: [12]
            sorting:
                name: asc
            fields:
                name:
                    type: string
                    sortable: null
            filters:
                taxon:
                    type: taxon_filter
    templates:
        filter:
            taxon_filter: 'frontend/pet/filters/_taxon_filter.html.twig'
