sylius_grid:
    grids:
        app_frontend_pet:
            driver:
                name: doctrine/orm
                options:
                    class: '%app.model.pet.class%'
                    repository:
                        method: createListQuerySlugBuilder
                        arguments: ['%locale%', $slug]
            limits: [12]
            sorting:
                name: asc
            fields:
                name:
                    type: string
                    sortable: null
            filters:
                taxon:
                    type: taxon_filter
                    label: app.ui.pet
                sex:
                    type: frontend_select
                    label: app.ui.sex
                    form_options:
                        choices:
                            app.ui.male: Male
                            app.ui.female: Female
                        multiple: true
                        expanded: true
                sizeRange:
                    type: frontend_select
                    label: app.ui.size
                    form_options:
                        choices:
                            app.ui.small: Small
                            app.ui.medium: Medium
                            app.ui.tall: Tall
                        multiple: true
                        expanded: true
    templates:
        filter:
            taxon_filter: 'frontend/pet/filters/_taxon_filter.html.twig'
