sylius_fixtures:
    suites:
        default:
            listeners:
                orm_purger: ~
                logger: ~

            fixtures:
                admin_user:
                    name: "admin_user"
                    options:
                        custom:
                            -
                                email: "admin@example.com"
                                password: "admin"
                                enabled: true
                                first_name: "John"
                                last_name: "Doe"

                app_user:
                   options:
                       custom:
                           -
                               email: "customer@example.com"
                               password: "password"
                               first_name: "Harry"
                               last_name: "Cover"
                               enabled: true
                       random: 10

                taxon:
                    options:
                        custom:
                                -
                                    name: Cats
                                    description: We could talk about their behavior for hours.
                                    children:
                                        -
                                            name: Persan
                                        -
                                            name: Siamese
                                        -
                                            name: Ragdoll
                                -
                                    name: Dogs
                                    description: They will bring you the ball back. Eventually.
                                    children:
                                        -
                                            name: Labrador
                                        -
                                            name: Poodle
                                        -
                                            name: Husky
                                -
                                    name: Small pets
                                    description: « They’re so fluffy I’m gonna die! »
                                    children:
                                        -
                                            name: Hamster
                                        -
                                            name: Rabbit

                pet:
                    options:
                        random: 100

                api_client:
                    options:
                        custom:
                            client:
                                allowed_grant_types: [password, access_token, refresh_token]
                                random_id: 5rbhrb0iiukokcwk8gow0w4ocgww0oco8g8gsgokwc0wcssg4w
                                secret: 2rlxzhijcx448ow4c0gksw4wo8oo4k8kkwwg0osskk8g0k8kw8

                booking:
                    options:
                        random: 20
