sylius_resource:
    resources:
        app.animal:
            driver: doctrine/orm
            classes:
                model: App\Entity\Animal\Animal
                form: App\Form\Type\Animal\AnimalType