sylius_resource:
    resources:
        app.pet:
            classes:
                model: App\Entity\Animal\Pet
                form: App\Form\Type\Animal\PetType
                repository: App\Repository\PetRepository
        app.pet_image:
            classes:
                model: App\Entity\Animal\PetImage
        app.booking:
            classes:
                model: App\Entity\Booking\Booking
                repository: App\Repository\BookingRepository
