sylius_resource:
    resources:
        app.animal:
            classes:
                model: App\Entity\Animal\Pet
                form: App\Form\Type\Animal\PetType
                repository: App\Repository\AnimalRepository
        app.animal_image:
            classes:
                model: App\Entity\Animal\PetImage
        app.booking:
            classes:
                model: App\Entity\Booking\Booking
                repository: App\Repository\BookingRepository
