sylius_resource:
    resources:
#        app.topic:
#            classes:
#                model: App\Entity\Topic\Topic
        app.pet:
            classes:
                model: App\Entity\Animal\Pet
                form: App\Form\Type\PetType
