sylius_resource:
    resources:
        app.booking:
            classes:
                model: App\Entity\Booking\Booking
        app.pet:
            classes:
                model: App\Entity\Animal\Pet
                form: App\Form\Type\Pet\PetType
