sylius_resource:
    resources:
        app.animal:
            classes:
                model: App\Entity\Animal\Animal
                form: App\Form\Type\Animal\AnimalType
        app.animal_image:
            classes:
                model: App\Entity\Animal\AnimalImage
        app.booking:
            classes:
                model: App\Entity\Booking\Booking
